[workspace]
resolver = "2"
members = [
  "services/api-gateway",
  "services/identity-service",
  "services/payment-service",
  "shared/domain",
  "shared/database",
  "shared/database/migration",
  "shared/kfintech-client",
  "shared/crypto",
  "shared/config",
  "shared/cache",
  "shared/logging",
  "shared/errors",
]

[workspace.dependencies]
actix-web = "4"
sea-orm = { version = "1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid", "with-chrono", "with-json"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "time", "fmt"] }
tracing-appender = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
redis = { version = "0.27", features = ["tokio-comp"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
anyhow = "1"
dotenvy = "0.15"
futures-util = "0.3"
regex = "1.11"
hmac = "0.12"
sha2 = "0.10"
md-5 = "0.10"
aes = "0.8"
cbc = { version = "0.1", features = ["alloc"] }
cipher = { version = "0.4", features = ["block-padding"] }
base64 = "0.22"
hex = "0.4"
rand = "0.8"
rsa = { version = "0.9", features = ["pem"] }
sha1 = "0.10"


[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
# Add custom clippy lints here for the entire workspace
enum_glob_use = "deny"
