[package]
name = "api-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
config = { path = "../../shared/config" }
logging = { path = "../../shared/logging" }
