use aes::Aes256;
use base64::prelude::*;
use cbc::cipher::{BlockDecryptMut, BlockEncryptMut, KeyIvInit, block_padding::Pkcs7};
use md5::{Digest, Md5};
use rand::RngCore;

type Aes256CbcEnc = cbc::Encryptor<Aes256>;
type Aes256CbcDec = cbc::Decryptor<Aes256>;

/// Errors that can occur during cryptographic operations.
#[derive(Debug, thiserror::Error)]
pub enum CryptoError {
    #[error("Invalid Base64 payload: {0}")]
    InvalidBase64(String),

    #[error("Invalid ciphertext header; expected 'Salted__' OpenSSL format")]
    InvalidCiphertextFormat,

    #[error("Decryption failed (bad key or corrupted padding): {0}")]
    DecryptionFailed(String),

    #[error("Decrypted payload is not valid UTF-8: {0}")]
    InvalidUtf8(String),

    #[error("JSON serialization error: {0}")]
    JsonError(#[from] serde_json::Error),
}

/// Implements OpenSSL's `EVP_BytesToKey` (EvpKDF with MD5 and 1 iteration).
///
/// This exact key derivation function is used by CryptoJS when encrypting or decrypting
/// with a string passphrase:
/// - `D_1 = MD5(password + salt)` (16 bytes)
/// - `D_2 = MD5(D_1 + password + salt)` (16 bytes)
/// - `D_3 = MD5(D_2 + password + salt)` (16 bytes)
///
/// Key = `D_1 || D_2` (32 bytes / 256 bits)
/// IV  = `D_3` (16 bytes / 128 bits)
fn evp_kdf(password: &[u8], salt: &[u8]) -> ([u8; 32], [u8; 16]) {
    // D_1
    let mut hasher = Md5::new();
    hasher.update(password);
    hasher.update(salt);
    let d1 = hasher.finalize();

    // D_2
    let mut hasher = Md5::new();
    hasher.update(&d1);
    hasher.update(password);
    hasher.update(salt);
    let d2 = hasher.finalize();

    // D_3
    let mut hasher = Md5::new();
    hasher.update(&d2);
    hasher.update(password);
    hasher.update(salt);
    let d3 = hasher.finalize();

    let mut key = [0u8; 32];
    key[..16].copy_from_slice(&d1);
    key[16..].copy_from_slice(&d2);

    let mut iv = [0u8; 16];
    iv.copy_from_slice(&d3);

    (key, iv)
}

/// Encrypts plaintext using AES-256-CBC matching CryptoJS `CryptoJS.AES.encrypt(plaintext, passphrase)`.
///
/// The output is an OpenSSL-compatible Base64-encoded string:
/// `b"Salted__"` (8 bytes) + 8-byte random salt + AES-256-CBC ciphertext with PKCS#7 padding.
pub fn encrypt_aes_cryptojs(plaintext: &str, passphrase: &str) -> Result<String, CryptoError> {
    let mut salt = [0u8; 8];
    rand::thread_rng().fill_bytes(&mut salt);

    let (key, iv) = evp_kdf(passphrase.as_bytes(), &salt);

    let encryptor = Aes256CbcEnc::new(&key.into(), &iv.into());
    let ciphertext = encryptor.encrypt_padded_vec_mut::<Pkcs7>(plaintext.as_bytes());

    let mut full = Vec::with_capacity(8 + 8 + ciphertext.len());
    full.extend_from_slice(b"Salted__");
    full.extend_from_slice(&salt);
    full.extend_from_slice(&ciphertext);

    Ok(BASE64_STANDARD.encode(full))
}

/// Decrypts a Base64-encoded ciphertext matching CryptoJS `CryptoJS.AES.decrypt(ciphertext, passphrase)`.
///
/// Expects the payload to start with `"Salted__"`, extracts the 8-byte salt, derives the key and IV
/// using OpenSSL EvpKDF, and decrypts the AES-256-CBC ciphertext with PKCS#7 unpadding.
pub fn decrypt_aes_cryptojs(ciphertext_b64: &str, passphrase: &str) -> Result<String, CryptoError> {
    let raw = BASE64_STANDARD
        .decode(ciphertext_b64.trim())
        .map_err(|e| CryptoError::InvalidBase64(e.to_string()))?;

    if raw.len() < 16 || &raw[..8] != b"Salted__" {
        return Err(CryptoError::InvalidCiphertextFormat);
    }

    let salt = &raw[8..16];
    let ciphertext = &raw[16..];

    let (key, iv) = evp_kdf(passphrase.as_bytes(), salt);

    let decryptor = Aes256CbcDec::new(&key.into(), &iv.into());
    let mut buf = ciphertext.to_vec();
    let decrypted = decryptor
        .decrypt_padded_mut::<Pkcs7>(&mut buf)
        .map_err(|e| CryptoError::DecryptionFailed(format!("{e:?}")))?;

    String::from_utf8(decrypted.to_vec()).map_err(|e| CryptoError::InvalidUtf8(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_roundtrip_encryption_decryption() {
        let passphrase = "aaa362430cc8b40f9ca4f3798dc008057cebb722a51e7771eed5a5fdafc4d976";
        let original_data = r#"{"name":"Virat","role":"Admin","amount":50000}"#;

        let encrypted = encrypt_aes_cryptojs(original_data, passphrase).expect("encryption failed");
        assert!(encrypted.starts_with("U2FsdGVkX1")); // b"Salted__" in base64!

        let decrypted = decrypt_aes_cryptojs(&encrypted, passphrase).expect("decryption failed");
        assert_eq!(decrypted, original_data);
    }

    #[test]
    fn test_decrypt_payload_generated_by_nodejs_cryptojs() {
        // Payload generated by NodeJS CryptoJS.AES.encrypt('{"hello":"world"}', password)
        let nodejs_ciphertext =
            "U2FsdGVkX18xMjM0NTY3OKOCgv8NBUIbFNulo4gltTX/kEOuOczVBSh+kKjCemqj";
        let passphrase = "aaa362430cc8b40f9ca4f3798dc008057cebb722a51e7771eed5a5fdafc4d976";

        let decrypted = decrypt_aes_cryptojs(nodejs_ciphertext, passphrase)
            .expect("decryption of NodeJS payload failed");
        assert_eq!(decrypted, r#"{"hello":"world"}"#);
    }

    #[test]
    fn test_decryption_with_wrong_key_fails() {
        let key1 = "aaa362430cc8b40f9ca4f3798dc008057cebb722a51e7771eed5a5fdafc4d976";
        let wrong_key = "d0f3313cdfa96d203cc081e11bbe1bf41b7887dbed7145cac717ca5f33074e00";

        let encrypted = encrypt_aes_cryptojs("sensitive data", key1).unwrap();
        let result = decrypt_aes_cryptojs(&encrypted, wrong_key);

        assert!(result.is_err());
    }

    #[test]
    fn test_invalid_base64_fails() {
        let key = "some_secret_key";
        let result = decrypt_aes_cryptojs("not-valid-base64!@#$", key);
        assert!(matches!(result, Err(CryptoError::InvalidBase64(_))));
    }

    #[test]
    fn test_missing_salted_header_fails() {
        let key = "some_secret_key";
        let fake_base64 = BASE64_STANDARD.encode(b"NotSaltedHeaderDataHere");
        let result = decrypt_aes_cryptojs(&fake_base64, key);
        assert!(matches!(result, Err(CryptoError::InvalidCiphertextFormat)));
    }
}
